/*
 * @Author: your name
 * @Date: 2024-03-21 10:23:03
 * @LastEditTime: 2024-03-21 14:36:26
 * @LastEditors: 韦玮莹
 * @Description: In User Settings Edit
 * @FilePath: \website\pages\statics\FAQs.tsx
 */import parse from 'html-react-parser';

import { useRouter } from "next/router";


export default function FAQs() {
  const router = useRouter();
  const list = [
    {
      title: '1.Can I send and receive emails from other mailboxes (Gmail, Outlook, etc.)?',
      desc: 'Of course! One of our goals is to connect Web2 and Web3 users without boundaries.'
    },
    {
      title: ' 2. Free to use ?',
      desc: `  Yes! MetaMail is totally free and without gas fees.
      Furthermore, MetaMail will not charge you any fees during your use.`
    },
    {
      title: `3. Need to register ?`,
      desc: `No.Just connect your wallet with our website.`
    }, {
      title: `4. Why need a signature when logging in? Will my wallet's private key beleaked in this step?`,
      desc: `(1)To verify the ownership of your address, you need to sign with your wallets
private key.<br>(2) It's safe to sign the message. MetaMail calls the wallet interface for signaturewithout revealing the wallet's private key, and the step is also free(without a gas fee)
  `
    }, {
      title: ` 5. Why do l need to have a non - zero ETH balance or nonce in my walletwhen logging in?`,
      desc: ` A non - Zer0 ETH balance or nonce in the address proves this address has someon - chain activities in history.This is a temporary POS - like mechanism to preventrobots from registering large numbers of addresses
      <br>
We will consider other mechanisms in the future to verify the validity of an address.<text class="text-[#006AD4]">Please contact us(metamail@mmail, ink) if you have some cool ideas!</text>
  `
    }, {
      title: `  6. How to get an email address with ENS:`,
      desc: ` A tutorial for registering ENS:<br> https: /supportens domainsen/articles, 7882582 - how - to - register`
    }, {
      title: `7. l have registered an ENS, but it doesn't show up?`,
      desc: ` (1)Make sure you have set the Primary ENS Name recordhttps:/support.ens domains/enarticles,7890756-the-primary-name
      <br>(2)And just log in again.`
    }, {
      title: `8. Where are mails stored ?`,
      desc: ` The mails are stored on our server.It is very secure because the signing andencryption of emails are completely done in the front end(the code is open - source)
 `
    }, {
      title: ` 9. What are email signatures and end - to - end encryption ?`,
      desc: `(1)An email signature is a number generated by the sender of the email.whichensures the integrity of the email and identifes the sender of the email(preventingimpersonation).
<br>(2) For clarity, end - to - end encryption means that the sender encrypts the email'scontent with a symmetric encryption kev, which is then encrypted with the recipient'spublic key, The recipient uses their private key to decrypt the symmetric key andsubsequently decrypts the email content with it.This ensures that no one else.except the sender and recipient, can access the content of the email
  `
    }, {
      title: `10.l transferred my ENS to others, will my historical emails be seen byothers ?`,
      desc: ` Absolutely not! We guarantee this in at least two aspects:
      <br>(1)Each time vour ENS mailbox sends or receives an email.it is stored in the inboxassociated with your unique ETH address(this is verifable on the blockchain).Wherthe ENS is linked to a new address, emails received after that point are directed tothe new address's inbox, Emails received before the transfer will not be visible in thenew inbox.
      <br>(2)lmportantly, your private keys related to MetaMail, which are derived from yourwallet's private key through a cryptographic process, remain securely with you.Thecontent of your emails cannot be decrypted even if others obtain the emails throughother means.
  `
    },]
  return (
    <>
      <div className="container max-w-[1024px] min-h-[100vh] mx-auto bg-[#F2F5F8] px-62 text-[#333] text-[16px] pt-56">
        <h2 className="mb-24 text-[#0069E5] text-[34px] font-[PoppinsBold]">Metamail</h2>
        <div>
          <ul className="bg-white p-32">
            <li className="mb-30"> <h5 className="font-bold ">MetaMail FAQs:</h5></li>
            {
              list.map(i => {
                return (
                  <li className="mb-30" key={i.title}>
                    <h6 className="font-bolder font-bold mb-5">
                      {i.title}
                    </h6>
                    <article className="text-14">
                      {parse(i.desc)}
                    </article>
                  </li>
                )
              })
            }

          </ul>
        </div>
      </div>
    </>

  )
}