/* eslint-disable react/no-children-prop */
/*
 * @Author: your name
 * @Date: 2024-03-21 10:23:03
 * @LastEditTime: 2024-03-21 14:36:26
 * @LastEditors: 韦玮莹
 * @Description: In User Settings Edit
 * @FilePath: \website\pages\statics\FAQs.tsx
 */

import MDRender from "../../components/MdRender/MdRender";
export default function FAQs() {

  // --------------------------------------------------------------
  const markdownText = `
# **MetaMail FAQs**
# &nbsp;
# &nbsp;
## **1.Can I send and receive emails from other mailboxes (Gmail, Outlook, etc.)?**
Of course! One of our goals is to connect Web2 and Web3 users without boundaries.
# &nbsp;
## **2.Free to use?**
Yes! MetaMail is totally free and without gas fees.
Furthermore, MetaMail will not charge you any fees during your use.
# &nbsp;
## **3.Need to register?**
No. Just connect your wallet with our website.
# &nbsp;

## **4.Why need a signature when logging in? Will my wallet’s private key be leaked in this step?**
(1) To verify the ownership of your address, you need to sign with your wallet’s private key.

(2) It’s safe to sign the message. MetaMail calls the wallet interface for signature without revealing the wallet’s private key, and the step is also free (without a gas fee).
# &nbsp;

## **5.Why do I need to have a non-zero ETH balance or nonce in my wallet when logging in?**
A non-zero ETH balance or nonce in the address proves this address has some on-chain activities in history. This is a temporary POS-like mechanism to prevent robots from registering large numbers of addresses.
We will consider other mechanisms in the future to verify the validity of an address. Please contact us (metamail@mmail.ink) if you have some cool ideas!
# &nbsp;

## **6.How to get an email address with ENS:**
A tutorial for registering ENS:
[https://support.ens.domains/en/articles/7882582-how-to-register](https://support.ens.domains/en/articles/7882582-how-to-register)
# &nbsp;

## **7.I have registered an ENS, but it doesn't show up?**
(1) Make sure you have set the Primary ENS Name record:
[https://support.ens.domains/en/articles/7890756-the-primary-name](https://support.ens.domains/en/articles/7890756-the-primary-name)

(2) And just log in again.
# &nbsp;
## **8.Where are mails stored?**
The mails are stored on our server. It is very secure because the signing and encryption of emails are completely done in the front end (the code is open-source).
# &nbsp;
## **9.What are email signatures and end-to-end encryption?**
(1) An email signature is a number generated by the sender of the email, which ensures the integrity of the email and identifies the sender of the email (preventing impersonation).

(2) For clarity, end-to-end encryption means that the sender encrypts the email's content with a symmetric encryption key, which is then encrypted with the recipient's public key. The recipient uses their private key to decrypt the symmetric key and subsequently decrypts the email content with it. This ensures that no one else, except the sender and recipient, can access the content of the email.
# &nbsp;
## **10.I transferred my ENS to others, will my historical emails be seen by others?**
Absolutely not! We guarantee this in at least two aspects:

(1) Each time your ENS mailbox sends or receives an email, it is stored in the inbox associated with your unique ETH address (this is verifiable on the blockchain). When the ENS is linked to a new address, emails received after that point are directed to the new address's inbox. Emails received before the transfer will not be visible in the new inbox.

(2) Importantly, your private keys related to MetaMail, which are derived from your wallet's private key through a cryptographic process, remain securely with you. The content of your emails cannot be decrypted even if others obtain the emails through other means.

`;
  // --------------------------------------------------------------
  return (
    <>
      <MDRender
        markdownText={markdownText}
      />
    </>

  )
}